[workspace]
resolver = "2"
members = [
    "aoc_lib",
    "day1",
    "day2",
    "day3",
    "day4",
    "day5",
]

[workspace.dependencies]
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
glam = "0.24"
